
services:
  database_api:
    build:
      context: ./database
    ports:
      - "8001:8001"
    env_file:
      - ./database/.env
    restart: always

  backend_api:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_API_URL=http://database_api:8001
      - FRONTEND_ORIGIN=http://localhost:5173
    depends_on:
      - database_api
    restart: always

  frontend_app:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend_api
    restart: always
