version: '3.8'

services:
  backend_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_API_URL=http://host.docker.internal:8001
      - FRONTEND_ORIGIN=http://localhost:5173
