# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases
from ._compat import model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED

if TYPE_CHECKING:
    from .client import Prisma
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class PublicationActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.Publication]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await Publication.prisma().query_raw(
            'SELECT * FROM Publication WHERE id = $1',
            1103527590,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.Publication
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await Publication.prisma().query_first(
            'SELECT * FROM Publication WHERE text_content = $1',
            'dhheabfhf',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.PublicationCreateInput,
        include: Optional[types.PublicationInclude] = None
    ) -> _PrismaModelT:
        """Create a new Publication record.

        Parameters
        ----------
        data
            Publication record data
        include
            Specifies which relations should be loaded on the returned Publication model

        Returns
        -------
        prisma.models.Publication
            The created Publication record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a Publication record from just the required fields
        publication = await Publication.prisma().create(
            data={
                # data to create a Publication record
                'text_content': 'ggciceaie',
                'text_content_en': 'bbehjachib',
                'is_real': True,
                'mil_tip': 'dgiiaaijj',
                'mil_tip_en': 'bfaiacjjfc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.PublicationCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple Publication records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of Publication record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await Publication.prisma().create_many(
            data=[
                {
                    # data to create a Publication record
                    'text_content': 'eigcfgbif',
                    'text_content_en': 'bagcfbhiig',
                    'is_real': False,
                    'mil_tip': 'biabhbdai',
                    'mil_tip_en': 'idghgaicb',
                },
                {
                    # data to create a Publication record
                    'text_content': 'fjfddhigg',
                    'text_content_en': 'hjaecfifb',
                    'is_real': True,
                    'mil_tip': 'bbejhfidcb',
                    'mil_tip_en': 'bgeecijdgg',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.PublicationWhereUniqueInput,
        include: Optional[types.PublicationInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single Publication record.

        Parameters
        ----------
        where
            Publication filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned Publication model

        Returns
        -------
        prisma.models.Publication
            The deleted Publication record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        publication = await Publication.prisma().delete(
            where={
                'id': 1388290519,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.PublicationWhereUniqueInput,
        include: Optional[types.PublicationInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique Publication record.

        Parameters
        ----------
        where
            Publication filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Publication model

        Returns
        -------
        prisma.models.Publication
            The found Publication record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        publication = await Publication.prisma().find_unique(
            where={
                'id': 1647418052,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.PublicationWhereUniqueInput,
        include: Optional[types.PublicationInclude] = None
    ) -> _PrismaModelT:
        """Find a unique Publication record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            Publication filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Publication model

        Returns
        -------
        prisma.models.Publication
            The found Publication record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        publication = await Publication.prisma().find_unique_or_raise(
            where={
                'id': 1675546029,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PublicationWhereInput] = None,
        cursor: Optional[types.PublicationWhereUniqueInput] = None,
        include: Optional[types.PublicationInclude] = None,
        order: Optional[Union[types.PublicationOrderByInput, List[types.PublicationOrderByInput]]] = None,
        distinct: Optional[List[types.PublicationScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple Publication records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of Publication records returned
        skip
            Ignore the first N results
        where
            Publication filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Publication model
        order
            Order the returned Publication records by any field
        distinct
            Filter Publication records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.Publication]
            The list of all Publication records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 Publication records
        publications = await Publication.prisma().find_many(take=10)

        # find the first 5 Publication records ordered by the text_content_en field
        publications = await Publication.prisma().find_many(
            take=5,
            order={
                'text_content_en': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.PublicationWhereInput] = None,
        cursor: Optional[types.PublicationWhereUniqueInput] = None,
        include: Optional[types.PublicationInclude] = None,
        order: Optional[Union[types.PublicationOrderByInput, List[types.PublicationOrderByInput]]] = None,
        distinct: Optional[List[types.PublicationScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single Publication record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Publication filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Publication model
        order
            Order the returned Publication records by any field
        distinct
            Filter Publication records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Publication
            The first Publication record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Publication record ordered by the media_url field
        publication = await Publication.prisma().find_first(
            skip=1,
            order={
                'media_url': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.PublicationWhereInput] = None,
        cursor: Optional[types.PublicationWhereUniqueInput] = None,
        include: Optional[types.PublicationInclude] = None,
        order: Optional[Union[types.PublicationOrderByInput, List[types.PublicationOrderByInput]]] = None,
        distinct: Optional[List[types.PublicationScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single Publication record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Publication filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Publication model
        order
            Order the returned Publication records by any field
        distinct
            Filter Publication records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Publication
            The first Publication record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Publication record ordered by the is_real field
        publication = await Publication.prisma().find_first_or_raise(
            skip=1,
            order={
                'is_real': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.PublicationUpdateInput,
        where: types.PublicationWhereUniqueInput,
        include: Optional[types.PublicationInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single Publication record.

        Parameters
        ----------
        data
            Publication record data specifying what to update
        where
            Publication filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned Publication model

        Returns
        -------
        prisma.models.Publication
            The updated Publication record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        publication = await Publication.prisma().update(
            where={
                'id': 1767274722,
            },
            data={
                # data to update the Publication record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.PublicationWhereUniqueInput,
        data: types.PublicationUpsertInput,
        include: Optional[types.PublicationInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            Publication filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned Publication model

        Returns
        -------
        prisma.models.Publication
            The created or updated Publication record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        publication = await Publication.prisma().upsert(
            where={
                'id': 326272115,
            },
            data={
                'create': {
                    'id': 326272115,
                    'text_content': 'fjfddhigg',
                    'text_content_en': 'hjaecfifb',
                    'is_real': True,
                    'mil_tip': 'bbejhfidcb',
                    'mil_tip_en': 'bgeecijdgg',
                },
                'update': {
                    'text_content': 'fjfddhigg',
                    'text_content_en': 'hjaecfifb',
                    'is_real': True,
                    'mil_tip': 'bbejhfidcb',
                    'mil_tip_en': 'bgeecijdgg',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.PublicationUpdateManyMutationInput,
        where: types.PublicationWhereInput,
    ) -> int:
        """Update multiple Publication records

        Parameters
        ----------
        data
            Publication data to update the selected Publication records to
        where
            Filter to select the Publication records to update

        Returns
        -------
        int
            The total number of Publication records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all Publication records
        total = await Publication.prisma().update_many(
            data={
                'mil_tip': 'bdedcabahc'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PublicationWhereInput] = None,
        cursor: Optional[types.PublicationWhereUniqueInput] = None,
    ) -> int:
        """Count the number of Publication records present in the database

        Parameters
        ----------
        select
            Select the Publication fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Publication filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.PublicationCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Publication.prisma().count()

        # results: prisma.types.PublicationCountAggregateOutput
        results = await Publication.prisma().count(
            select={
                '_all': True,
                'mil_tip_en': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.PublicationCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PublicationWhereInput] = None,
        cursor: Optional[types.PublicationWhereUniqueInput] = None,
    ) -> types.PublicationCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.PublicationCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PublicationWhereInput] = None,
        cursor: Optional[types.PublicationWhereUniqueInput] = None,
    ) -> Union[int, types.PublicationCountAggregateOutput]:
        """Count the number of Publication records present in the database

        Parameters
        ----------
        select
            Select the Publication fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Publication filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.PublicationCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Publication.prisma().count()

        # results: prisma.types.PublicationCountAggregateOutput
        results = await Publication.prisma().count(
            select={
                '_all': True,
                'category': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.PublicationCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.PublicationWhereInput] = None
    ) -> int:
        """Delete multiple Publication records.

        Parameters
        ----------
        where
            Optional Publication filter to find the records to be deleted

        Returns
        -------
        int
            The total number of Publication records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all Publication records
        total = await Publication.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.PublicationScalarFieldKeys'],
        *,
        where: Optional['types.PublicationWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.PublicationAvgAggregateInput'] = None,
        sum: Optional['types.PublicationSumAggregateInput'] = None,
        min: Optional['types.PublicationMinAggregateInput'] = None,
        max: Optional['types.PublicationMaxAggregateInput'] = None,
        having: Optional['types.PublicationScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.PublicationCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.PublicationScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.PublicationScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.PublicationGroupByOutput']:
        """Group Publication records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar Publication fields to group records by
        where
            Publication filter to select records
        take
            Limit the maximum number of Publication records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.PublicationGroupByOutput]
            A list of dictionaries representing the Publication record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group Publication records by author_name values
        # and count how many records are in each group
        results = await Publication.prisma().group_by(
            ['author_name'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]


class LeaderboardEntryActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.LeaderboardEntry]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await LeaderboardEntry.prisma().query_raw(
            'SELECT * FROM LeaderboardEntry WHERE id = $1',
            675780521,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.LeaderboardEntry
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await LeaderboardEntry.prisma().query_first(
            'SELECT * FROM LeaderboardEntry WHERE player_name = $1',
            'heejgedji',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.LeaderboardEntryCreateInput,
        include: Optional[types.LeaderboardEntryInclude] = None
    ) -> _PrismaModelT:
        """Create a new LeaderboardEntry record.

        Parameters
        ----------
        data
            LeaderboardEntry record data
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model

        Returns
        -------
        prisma.models.LeaderboardEntry
            The created LeaderboardEntry record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a LeaderboardEntry record from just the required fields
        leaderboardentry = await LeaderboardEntry.prisma().create(
            data={
                # data to create a LeaderboardEntry record
                'player_name': 'bjgjgibgbf',
                'score': 1116175964,
                'correct': 861472101,
                'wrong': 1303003706,
                'omitted': 1686638315,
                'accuracy_pct': 2000430152.186814,
                'duration_s': 1860847622,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.LeaderboardEntryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple LeaderboardEntry records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of LeaderboardEntry record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await LeaderboardEntry.prisma().create_many(
            data=[
                {
                    # data to create a LeaderboardEntry record
                    'player_name': 'beeifcbebf',
                    'score': 1628650740,
                    'correct': 1249606685,
                    'wrong': 835903122,
                    'omitted': 763719779,
                    'accuracy_pct': 429995104.177581,
                    'duration_s': 893145566,
                },
                {
                    # data to create a LeaderboardEntry record
                    'player_name': 'jjfeafhfj',
                    'score': 2102736524,
                    'correct': 271520213,
                    'wrong': 456633834,
                    'omitted': 2058258651,
                    'accuracy_pct': 1583689592.87844,
                    'duration_s': 1675280054,
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.LeaderboardEntryWhereUniqueInput,
        include: Optional[types.LeaderboardEntryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single LeaderboardEntry record.

        Parameters
        ----------
        where
            LeaderboardEntry filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model

        Returns
        -------
        prisma.models.LeaderboardEntry
            The deleted LeaderboardEntry record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        leaderboardentry = await LeaderboardEntry.prisma().delete(
            where={
                'id': 1627576247,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.LeaderboardEntryWhereUniqueInput,
        include: Optional[types.LeaderboardEntryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique LeaderboardEntry record.

        Parameters
        ----------
        where
            LeaderboardEntry filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model

        Returns
        -------
        prisma.models.LeaderboardEntry
            The found LeaderboardEntry record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        leaderboardentry = await LeaderboardEntry.prisma().find_unique(
            where={
                'id': 2054802212,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.LeaderboardEntryWhereUniqueInput,
        include: Optional[types.LeaderboardEntryInclude] = None
    ) -> _PrismaModelT:
        """Find a unique LeaderboardEntry record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            LeaderboardEntry filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model

        Returns
        -------
        prisma.models.LeaderboardEntry
            The found LeaderboardEntry record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        leaderboardentry = await LeaderboardEntry.prisma().find_unique_or_raise(
            where={
                'id': 60335757,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.LeaderboardEntryWhereInput] = None,
        cursor: Optional[types.LeaderboardEntryWhereUniqueInput] = None,
        include: Optional[types.LeaderboardEntryInclude] = None,
        order: Optional[Union[types.LeaderboardEntryOrderByInput, List[types.LeaderboardEntryOrderByInput]]] = None,
        distinct: Optional[List[types.LeaderboardEntryScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple LeaderboardEntry records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of LeaderboardEntry records returned
        skip
            Ignore the first N results
        where
            LeaderboardEntry filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model
        order
            Order the returned LeaderboardEntry records by any field
        distinct
            Filter LeaderboardEntry records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.LeaderboardEntry]
            The list of all LeaderboardEntry records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 LeaderboardEntry records
        leaderboardentrys = await LeaderboardEntry.prisma().find_many(take=10)

        # find the first 5 LeaderboardEntry records ordered by the score field
        leaderboardentrys = await LeaderboardEntry.prisma().find_many(
            take=5,
            order={
                'score': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.LeaderboardEntryWhereInput] = None,
        cursor: Optional[types.LeaderboardEntryWhereUniqueInput] = None,
        include: Optional[types.LeaderboardEntryInclude] = None,
        order: Optional[Union[types.LeaderboardEntryOrderByInput, List[types.LeaderboardEntryOrderByInput]]] = None,
        distinct: Optional[List[types.LeaderboardEntryScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single LeaderboardEntry record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            LeaderboardEntry filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model
        order
            Order the returned LeaderboardEntry records by any field
        distinct
            Filter LeaderboardEntry records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.LeaderboardEntry
            The first LeaderboardEntry record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second LeaderboardEntry record ordered by the correct field
        leaderboardentry = await LeaderboardEntry.prisma().find_first(
            skip=1,
            order={
                'correct': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.LeaderboardEntryWhereInput] = None,
        cursor: Optional[types.LeaderboardEntryWhereUniqueInput] = None,
        include: Optional[types.LeaderboardEntryInclude] = None,
        order: Optional[Union[types.LeaderboardEntryOrderByInput, List[types.LeaderboardEntryOrderByInput]]] = None,
        distinct: Optional[List[types.LeaderboardEntryScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single LeaderboardEntry record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            LeaderboardEntry filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model
        order
            Order the returned LeaderboardEntry records by any field
        distinct
            Filter LeaderboardEntry records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.LeaderboardEntry
            The first LeaderboardEntry record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second LeaderboardEntry record ordered by the wrong field
        leaderboardentry = await LeaderboardEntry.prisma().find_first_or_raise(
            skip=1,
            order={
                'wrong': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.LeaderboardEntryUpdateInput,
        where: types.LeaderboardEntryWhereUniqueInput,
        include: Optional[types.LeaderboardEntryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single LeaderboardEntry record.

        Parameters
        ----------
        data
            LeaderboardEntry record data specifying what to update
        where
            LeaderboardEntry filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model

        Returns
        -------
        prisma.models.LeaderboardEntry
            The updated LeaderboardEntry record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        leaderboardentry = await LeaderboardEntry.prisma().update(
            where={
                'id': 684462146,
            },
            data={
                # data to update the LeaderboardEntry record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.LeaderboardEntryWhereUniqueInput,
        data: types.LeaderboardEntryUpsertInput,
        include: Optional[types.LeaderboardEntryInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            LeaderboardEntry filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned LeaderboardEntry model

        Returns
        -------
        prisma.models.LeaderboardEntry
            The created or updated LeaderboardEntry record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        leaderboardentry = await LeaderboardEntry.prisma().upsert(
            where={
                'id': 1625503827,
            },
            data={
                'create': {
                    'id': 1625503827,
                    'player_name': 'jjfeafhfj',
                    'score': 2102736524,
                    'correct': 271520213,
                    'wrong': 456633834,
                    'omitted': 2058258651,
                    'accuracy_pct': 1583689592.87844,
                    'duration_s': 1675280054,
                },
                'update': {
                    'player_name': 'jjfeafhfj',
                    'score': 2102736524,
                    'correct': 271520213,
                    'wrong': 456633834,
                    'omitted': 2058258651,
                    'accuracy_pct': 1583689592.87844,
                    'duration_s': 1675280054,
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.LeaderboardEntryUpdateManyMutationInput,
        where: types.LeaderboardEntryWhereInput,
    ) -> int:
        """Update multiple LeaderboardEntry records

        Parameters
        ----------
        data
            LeaderboardEntry data to update the selected LeaderboardEntry records to
        where
            Filter to select the LeaderboardEntry records to update

        Returns
        -------
        int
            The total number of LeaderboardEntry records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all LeaderboardEntry records
        total = await LeaderboardEntry.prisma().update_many(
            data={
                'omitted': 521827728
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.LeaderboardEntryWhereInput] = None,
        cursor: Optional[types.LeaderboardEntryWhereUniqueInput] = None,
    ) -> int:
        """Count the number of LeaderboardEntry records present in the database

        Parameters
        ----------
        select
            Select the LeaderboardEntry fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            LeaderboardEntry filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.LeaderboardEntryCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await LeaderboardEntry.prisma().count()

        # results: prisma.types.LeaderboardEntryCountAggregateOutput
        results = await LeaderboardEntry.prisma().count(
            select={
                '_all': True,
                'accuracy_pct': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.LeaderboardEntryCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.LeaderboardEntryWhereInput] = None,
        cursor: Optional[types.LeaderboardEntryWhereUniqueInput] = None,
    ) -> types.LeaderboardEntryCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.LeaderboardEntryCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.LeaderboardEntryWhereInput] = None,
        cursor: Optional[types.LeaderboardEntryWhereUniqueInput] = None,
    ) -> Union[int, types.LeaderboardEntryCountAggregateOutput]:
        """Count the number of LeaderboardEntry records present in the database

        Parameters
        ----------
        select
            Select the LeaderboardEntry fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            LeaderboardEntry filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.LeaderboardEntryCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await LeaderboardEntry.prisma().count()

        # results: prisma.types.LeaderboardEntryCountAggregateOutput
        results = await LeaderboardEntry.prisma().count(
            select={
                '_all': True,
                'duration_s': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.LeaderboardEntryCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.LeaderboardEntryWhereInput] = None
    ) -> int:
        """Delete multiple LeaderboardEntry records.

        Parameters
        ----------
        where
            Optional LeaderboardEntry filter to find the records to be deleted

        Returns
        -------
        int
            The total number of LeaderboardEntry records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all LeaderboardEntry records
        total = await LeaderboardEntry.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.LeaderboardEntryScalarFieldKeys'],
        *,
        where: Optional['types.LeaderboardEntryWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.LeaderboardEntryAvgAggregateInput'] = None,
        sum: Optional['types.LeaderboardEntrySumAggregateInput'] = None,
        min: Optional['types.LeaderboardEntryMinAggregateInput'] = None,
        max: Optional['types.LeaderboardEntryMaxAggregateInput'] = None,
        having: Optional['types.LeaderboardEntryScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.LeaderboardEntryCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.LeaderboardEntryScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.LeaderboardEntryScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.LeaderboardEntryGroupByOutput']:
        """Group LeaderboardEntry records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar LeaderboardEntry fields to group records by
        where
            LeaderboardEntry filter to select records
        take
            Limit the maximum number of LeaderboardEntry records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.LeaderboardEntryGroupByOutput]
            A list of dictionaries representing the LeaderboardEntry record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group LeaderboardEntry records by created_at values
        # and count how many records are in each group
        results = await LeaderboardEntry.prisma().group_by(
            ['created_at'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models