# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# Publication types

class PublicationOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Publication create method"""
    id: _int
    media_url: Optional[_str]
    category: Optional[_str]
    author_name: Optional[_str]
    author_handle: Optional[_str]
    likes_count: _int
    created_at: datetime.datetime


class PublicationCreateInput(PublicationOptionalCreateInput):
    """Required arguments to the Publication create method"""
    text_content: _str
    text_content_en: _str
    is_real: _bool
    mil_tip: _str
    mil_tip_en: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class PublicationOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Publication create method, without relations"""
    id: _int
    media_url: Optional[_str]
    category: Optional[_str]
    author_name: Optional[_str]
    author_handle: Optional[_str]
    likes_count: _int
    created_at: datetime.datetime


class PublicationCreateWithoutRelationsInput(PublicationOptionalCreateWithoutRelationsInput):
    """Required arguments to the Publication create method, without relations"""
    text_content: _str
    text_content_en: _str
    is_real: _bool
    mil_tip: _str
    mil_tip_en: _str

class PublicationConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'PublicationCreateWithoutRelationsInput'
    where: 'PublicationWhereUniqueInput'

class PublicationCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'PublicationCreateWithoutRelationsInput'
    connect: 'PublicationWhereUniqueInput'
    connect_or_create: 'PublicationConnectOrCreateWithoutRelationsInput'


class PublicationCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['PublicationCreateWithoutRelationsInput', List['PublicationCreateWithoutRelationsInput']]
    connect: Union['PublicationWhereUniqueInput', List['PublicationWhereUniqueInput']]
    connect_or_create: Union['PublicationConnectOrCreateWithoutRelationsInput', List['PublicationConnectOrCreateWithoutRelationsInput']]

_PublicationWhereUnique_id_Input = TypedDict(
    '_PublicationWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

PublicationWhereUniqueInput = _PublicationWhereUnique_id_Input


class PublicationUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    text_content: _str
    text_content_en: _str
    media_url: Optional[_str]
    is_real: _bool
    mil_tip: _str
    mil_tip_en: _str
    category: Optional[_str]
    author_name: Optional[_str]
    author_handle: Optional[_str]
    likes_count: Union[AtomicIntInput, _int]
    created_at: datetime.datetime


class PublicationUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    text_content: _str
    text_content_en: _str
    media_url: Optional[_str]
    is_real: _bool
    mil_tip: _str
    mil_tip_en: _str
    category: Optional[_str]
    author_name: Optional[_str]
    author_handle: Optional[_str]
    likes_count: Union[AtomicIntInput, _int]
    created_at: datetime.datetime


class PublicationUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['PublicationCreateWithoutRelationsInput']
    connect: List['PublicationWhereUniqueInput']
    connect_or_create: List['PublicationConnectOrCreateWithoutRelationsInput']
    set: List['PublicationWhereUniqueInput']
    disconnect: List['PublicationWhereUniqueInput']
    delete: List['PublicationWhereUniqueInput']

    # TODO
    # update: List['PublicationUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['PublicationUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['PublicationScalarWhereInput']
    # upsert: List['PublicationUpserteWithWhereUniqueWithoutRelationsInput']


class PublicationUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'PublicationCreateWithoutRelationsInput'
    connect: 'PublicationWhereUniqueInput'
    connect_or_create: 'PublicationConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'PublicationUpdateInput'
    # upsert: 'PublicationUpsertWithoutRelationsInput'


class PublicationUpsertInput(TypedDict):
    create: 'PublicationCreateInput'
    update: 'PublicationUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Publication_id_OrderByInput = TypedDict(
    '_Publication_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Publication_text_content_OrderByInput = TypedDict(
    '_Publication_text_content_OrderByInput',
    {
        'text_content': 'SortOrder',
    },
    total=True
)

_Publication_text_content_en_OrderByInput = TypedDict(
    '_Publication_text_content_en_OrderByInput',
    {
        'text_content_en': 'SortOrder',
    },
    total=True
)

_Publication_media_url_OrderByInput = TypedDict(
    '_Publication_media_url_OrderByInput',
    {
        'media_url': 'SortOrder',
    },
    total=True
)

_Publication_is_real_OrderByInput = TypedDict(
    '_Publication_is_real_OrderByInput',
    {
        'is_real': 'SortOrder',
    },
    total=True
)

_Publication_mil_tip_OrderByInput = TypedDict(
    '_Publication_mil_tip_OrderByInput',
    {
        'mil_tip': 'SortOrder',
    },
    total=True
)

_Publication_mil_tip_en_OrderByInput = TypedDict(
    '_Publication_mil_tip_en_OrderByInput',
    {
        'mil_tip_en': 'SortOrder',
    },
    total=True
)

_Publication_category_OrderByInput = TypedDict(
    '_Publication_category_OrderByInput',
    {
        'category': 'SortOrder',
    },
    total=True
)

_Publication_author_name_OrderByInput = TypedDict(
    '_Publication_author_name_OrderByInput',
    {
        'author_name': 'SortOrder',
    },
    total=True
)

_Publication_author_handle_OrderByInput = TypedDict(
    '_Publication_author_handle_OrderByInput',
    {
        'author_handle': 'SortOrder',
    },
    total=True
)

_Publication_likes_count_OrderByInput = TypedDict(
    '_Publication_likes_count_OrderByInput',
    {
        'likes_count': 'SortOrder',
    },
    total=True
)

_Publication_created_at_OrderByInput = TypedDict(
    '_Publication_created_at_OrderByInput',
    {
        'created_at': 'SortOrder',
    },
    total=True
)

_Publication_RelevanceInner = TypedDict(
    '_Publication_RelevanceInner',
    {
        'fields': 'List[PublicationScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Publication_RelevanceOrderByInput = TypedDict(
    '_Publication_RelevanceOrderByInput',
    {
        '_relevance': '_Publication_RelevanceInner',
    },
    total=True
)

PublicationOrderByInput = Union[
    '_Publication_id_OrderByInput',
    '_Publication_text_content_OrderByInput',
    '_Publication_text_content_en_OrderByInput',
    '_Publication_media_url_OrderByInput',
    '_Publication_is_real_OrderByInput',
    '_Publication_mil_tip_OrderByInput',
    '_Publication_mil_tip_en_OrderByInput',
    '_Publication_category_OrderByInput',
    '_Publication_author_name_OrderByInput',
    '_Publication_author_handle_OrderByInput',
    '_Publication_likes_count_OrderByInput',
    '_Publication_created_at_OrderByInput',
    '_Publication_RelevanceOrderByInput',
]



# recursive Publication types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

PublicationRelationFilter = TypedDict(
    'PublicationRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class PublicationListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class PublicationInclude(TypedDict, total=False):
    """Publication relational arguments"""


    

class PublicationIncludeFromPublication(TypedDict, total=False):
    """Relational arguments for Publication"""


class PublicationIncludeFromPublicationRecursive1(TypedDict, total=False):
    """Relational arguments for Publication"""


class PublicationIncludeFromPublicationRecursive2(TypedDict, total=False):
    """Relational arguments for Publication"""


class PublicationIncludeFromPublicationRecursive3(TypedDict, total=False):
    """Relational arguments for Publication"""


class PublicationIncludeFromPublicationRecursive4(TypedDict, total=False):
    """Relational arguments for Publication"""

    

class PublicationArgsFromPublication(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'PublicationIncludeFromPublicationRecursive1'


class PublicationArgsFromPublicationRecursive1(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'PublicationIncludeFromPublicationRecursive2'


class PublicationArgsFromPublicationRecursive2(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'PublicationIncludeFromPublicationRecursive3'


class PublicationArgsFromPublicationRecursive3(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'PublicationIncludeFromPublicationRecursive4'


class PublicationArgsFromPublicationRecursive4(TypedDict, total=False):
    """Arguments for Publication"""
    
    

class FindManyPublicationArgsFromPublication(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive1'


class FindManyPublicationArgsFromPublicationRecursive1(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive2'


class FindManyPublicationArgsFromPublicationRecursive2(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive3'


class FindManyPublicationArgsFromPublicationRecursive3(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive4'


class FindManyPublicationArgsFromPublicationRecursive4(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    
    

class LeaderboardEntryIncludeFromPublication(TypedDict, total=False):
    """Relational arguments for Publication"""


class LeaderboardEntryIncludeFromPublicationRecursive1(TypedDict, total=False):
    """Relational arguments for Publication"""


class LeaderboardEntryIncludeFromPublicationRecursive2(TypedDict, total=False):
    """Relational arguments for Publication"""


class LeaderboardEntryIncludeFromPublicationRecursive3(TypedDict, total=False):
    """Relational arguments for Publication"""


class LeaderboardEntryIncludeFromPublicationRecursive4(TypedDict, total=False):
    """Relational arguments for Publication"""

    

class LeaderboardEntryArgsFromPublication(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive1'


class LeaderboardEntryArgsFromPublicationRecursive1(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive2'


class LeaderboardEntryArgsFromPublicationRecursive2(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive3'


class LeaderboardEntryArgsFromPublicationRecursive3(TypedDict, total=False):
    """Arguments for Publication"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive4'


class LeaderboardEntryArgsFromPublicationRecursive4(TypedDict, total=False):
    """Arguments for Publication"""
    
    

class FindManyLeaderboardEntryArgsFromPublication(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive1'


class FindManyLeaderboardEntryArgsFromPublicationRecursive1(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive2'


class FindManyLeaderboardEntryArgsFromPublicationRecursive2(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive3'


class FindManyLeaderboardEntryArgsFromPublicationRecursive3(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive4'


class FindManyLeaderboardEntryArgsFromPublicationRecursive4(TypedDict, total=False):
    """Arguments for Publication"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    


FindManyPublicationArgs = FindManyPublicationArgsFromPublication
FindFirstPublicationArgs = FindManyPublicationArgsFromPublication


    

class PublicationWhereInput(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    text_content: Union[_str, 'types.StringFilter']
    text_content_en: Union[_str, 'types.StringFilter']
    media_url: Union[None, _str, 'types.StringFilter']
    is_real: Union[_bool, 'types.BooleanFilter']
    mil_tip: Union[_str, 'types.StringFilter']
    mil_tip_en: Union[_str, 'types.StringFilter']
    category: Union[None, _str, 'types.StringFilter']
    author_name: Union[None, _str, 'types.StringFilter']
    author_handle: Union[None, _str, 'types.StringFilter']
    likes_count: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['PublicationWhereInputRecursive1', List['PublicationWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['PublicationWhereInputRecursive1']
    OR: List['PublicationWhereInputRecursive1']
    NOT: List['PublicationWhereInputRecursive1']


class PublicationWhereInputRecursive1(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    text_content: Union[_str, 'types.StringFilter']
    text_content_en: Union[_str, 'types.StringFilter']
    media_url: Union[None, _str, 'types.StringFilter']
    is_real: Union[_bool, 'types.BooleanFilter']
    mil_tip: Union[_str, 'types.StringFilter']
    mil_tip_en: Union[_str, 'types.StringFilter']
    category: Union[None, _str, 'types.StringFilter']
    author_name: Union[None, _str, 'types.StringFilter']
    author_handle: Union[None, _str, 'types.StringFilter']
    likes_count: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['PublicationWhereInputRecursive2', List['PublicationWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['PublicationWhereInputRecursive2']
    OR: List['PublicationWhereInputRecursive2']
    NOT: List['PublicationWhereInputRecursive2']


class PublicationWhereInputRecursive2(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    text_content: Union[_str, 'types.StringFilter']
    text_content_en: Union[_str, 'types.StringFilter']
    media_url: Union[None, _str, 'types.StringFilter']
    is_real: Union[_bool, 'types.BooleanFilter']
    mil_tip: Union[_str, 'types.StringFilter']
    mil_tip_en: Union[_str, 'types.StringFilter']
    category: Union[None, _str, 'types.StringFilter']
    author_name: Union[None, _str, 'types.StringFilter']
    author_handle: Union[None, _str, 'types.StringFilter']
    likes_count: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['PublicationWhereInputRecursive3', List['PublicationWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['PublicationWhereInputRecursive3']
    OR: List['PublicationWhereInputRecursive3']
    NOT: List['PublicationWhereInputRecursive3']


class PublicationWhereInputRecursive3(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    text_content: Union[_str, 'types.StringFilter']
    text_content_en: Union[_str, 'types.StringFilter']
    media_url: Union[None, _str, 'types.StringFilter']
    is_real: Union[_bool, 'types.BooleanFilter']
    mil_tip: Union[_str, 'types.StringFilter']
    mil_tip_en: Union[_str, 'types.StringFilter']
    category: Union[None, _str, 'types.StringFilter']
    author_name: Union[None, _str, 'types.StringFilter']
    author_handle: Union[None, _str, 'types.StringFilter']
    likes_count: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['PublicationWhereInputRecursive4', List['PublicationWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['PublicationWhereInputRecursive4']
    OR: List['PublicationWhereInputRecursive4']
    NOT: List['PublicationWhereInputRecursive4']


class PublicationWhereInputRecursive4(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    text_content: Union[_str, 'types.StringFilter']
    text_content_en: Union[_str, 'types.StringFilter']
    media_url: Union[None, _str, 'types.StringFilter']
    is_real: Union[_bool, 'types.BooleanFilter']
    mil_tip: Union[_str, 'types.StringFilter']
    mil_tip_en: Union[_str, 'types.StringFilter']
    category: Union[None, _str, 'types.StringFilter']
    author_name: Union[None, _str, 'types.StringFilter']
    author_handle: Union[None, _str, 'types.StringFilter']
    likes_count: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']



# aggregate Publication types


    

class PublicationScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    text_content: Union[_str, 'types.StringWithAggregatesFilter']
    text_content_en: Union[_str, 'types.StringWithAggregatesFilter']
    media_url: Union[_str, 'types.StringWithAggregatesFilter']
    is_real: Union[_bool, 'types.BooleanWithAggregatesFilter']
    mil_tip: Union[_str, 'types.StringWithAggregatesFilter']
    mil_tip_en: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    author_name: Union[_str, 'types.StringWithAggregatesFilter']
    author_handle: Union[_str, 'types.StringWithAggregatesFilter']
    likes_count: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['PublicationScalarWhereWithAggregatesInputRecursive1']
    OR: List['PublicationScalarWhereWithAggregatesInputRecursive1']
    NOT: List['PublicationScalarWhereWithAggregatesInputRecursive1']


class PublicationScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    text_content: Union[_str, 'types.StringWithAggregatesFilter']
    text_content_en: Union[_str, 'types.StringWithAggregatesFilter']
    media_url: Union[_str, 'types.StringWithAggregatesFilter']
    is_real: Union[_bool, 'types.BooleanWithAggregatesFilter']
    mil_tip: Union[_str, 'types.StringWithAggregatesFilter']
    mil_tip_en: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    author_name: Union[_str, 'types.StringWithAggregatesFilter']
    author_handle: Union[_str, 'types.StringWithAggregatesFilter']
    likes_count: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['PublicationScalarWhereWithAggregatesInputRecursive2']
    OR: List['PublicationScalarWhereWithAggregatesInputRecursive2']
    NOT: List['PublicationScalarWhereWithAggregatesInputRecursive2']


class PublicationScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    text_content: Union[_str, 'types.StringWithAggregatesFilter']
    text_content_en: Union[_str, 'types.StringWithAggregatesFilter']
    media_url: Union[_str, 'types.StringWithAggregatesFilter']
    is_real: Union[_bool, 'types.BooleanWithAggregatesFilter']
    mil_tip: Union[_str, 'types.StringWithAggregatesFilter']
    mil_tip_en: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    author_name: Union[_str, 'types.StringWithAggregatesFilter']
    author_handle: Union[_str, 'types.StringWithAggregatesFilter']
    likes_count: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['PublicationScalarWhereWithAggregatesInputRecursive3']
    OR: List['PublicationScalarWhereWithAggregatesInputRecursive3']
    NOT: List['PublicationScalarWhereWithAggregatesInputRecursive3']


class PublicationScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    text_content: Union[_str, 'types.StringWithAggregatesFilter']
    text_content_en: Union[_str, 'types.StringWithAggregatesFilter']
    media_url: Union[_str, 'types.StringWithAggregatesFilter']
    is_real: Union[_bool, 'types.BooleanWithAggregatesFilter']
    mil_tip: Union[_str, 'types.StringWithAggregatesFilter']
    mil_tip_en: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    author_name: Union[_str, 'types.StringWithAggregatesFilter']
    author_handle: Union[_str, 'types.StringWithAggregatesFilter']
    likes_count: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['PublicationScalarWhereWithAggregatesInputRecursive4']
    OR: List['PublicationScalarWhereWithAggregatesInputRecursive4']
    NOT: List['PublicationScalarWhereWithAggregatesInputRecursive4']


class PublicationScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Publication arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    text_content: Union[_str, 'types.StringWithAggregatesFilter']
    text_content_en: Union[_str, 'types.StringWithAggregatesFilter']
    media_url: Union[_str, 'types.StringWithAggregatesFilter']
    is_real: Union[_bool, 'types.BooleanWithAggregatesFilter']
    mil_tip: Union[_str, 'types.StringWithAggregatesFilter']
    mil_tip_en: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    author_name: Union[_str, 'types.StringWithAggregatesFilter']
    author_handle: Union[_str, 'types.StringWithAggregatesFilter']
    likes_count: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class PublicationGroupByOutput(TypedDict, total=False):
    id: _int
    text_content: _str
    text_content_en: _str
    media_url: _str
    is_real: _bool
    mil_tip: _str
    mil_tip_en: _str
    category: _str
    author_name: _str
    author_handle: _str
    likes_count: _int
    created_at: datetime.datetime
    _sum: 'PublicationSumAggregateOutput'
    _avg: 'PublicationAvgAggregateOutput'
    _min: 'PublicationMinAggregateOutput'
    _max: 'PublicationMaxAggregateOutput'
    _count: 'PublicationCountAggregateOutput'


class PublicationAvgAggregateOutput(TypedDict, total=False):
    """Publication output for aggregating averages"""
    id: float
    likes_count: float


class PublicationSumAggregateOutput(TypedDict, total=False):
    """Publication output for aggregating sums"""
    id: _int
    likes_count: _int


class PublicationScalarAggregateOutput(TypedDict, total=False):
    """Publication output including scalar fields"""
    id: _int
    text_content: _str
    text_content_en: _str
    media_url: _str
    is_real: _bool
    mil_tip: _str
    mil_tip_en: _str
    category: _str
    author_name: _str
    author_handle: _str
    likes_count: _int
    created_at: datetime.datetime


PublicationMinAggregateOutput = PublicationScalarAggregateOutput
PublicationMaxAggregateOutput = PublicationScalarAggregateOutput


class PublicationMaxAggregateInput(TypedDict, total=False):
    """Publication input for aggregating by max"""
    id: bool
    text_content: bool
    text_content_en: bool
    media_url: bool
    is_real: bool
    mil_tip: bool
    mil_tip_en: bool
    category: bool
    author_name: bool
    author_handle: bool
    likes_count: bool
    created_at: bool


class PublicationMinAggregateInput(TypedDict, total=False):
    """Publication input for aggregating by min"""
    id: bool
    text_content: bool
    text_content_en: bool
    media_url: bool
    is_real: bool
    mil_tip: bool
    mil_tip_en: bool
    category: bool
    author_name: bool
    author_handle: bool
    likes_count: bool
    created_at: bool


class PublicationNumberAggregateInput(TypedDict, total=False):
    """Publication input for aggregating numbers"""
    id: bool
    likes_count: bool


PublicationAvgAggregateInput = PublicationNumberAggregateInput
PublicationSumAggregateInput = PublicationNumberAggregateInput


PublicationCountAggregateInput = TypedDict(
    'PublicationCountAggregateInput',
    {
        'id': bool,
        'text_content': bool,
        'text_content_en': bool,
        'media_url': bool,
        'is_real': bool,
        'mil_tip': bool,
        'mil_tip_en': bool,
        'category': bool,
        'author_name': bool,
        'author_handle': bool,
        'likes_count': bool,
        'created_at': bool,
        '_all': bool,
    },
    total=False,
)

PublicationCountAggregateOutput = TypedDict(
    'PublicationCountAggregateOutput',
    {
        'id': int,
        'text_content': int,
        'text_content_en': int,
        'media_url': int,
        'is_real': int,
        'mil_tip': int,
        'mil_tip_en': int,
        'category': int,
        'author_name': int,
        'author_handle': int,
        'likes_count': int,
        'created_at': int,
        '_all': int,
    },
    total=False,
)


PublicationKeys = Literal[
    'id',
    'text_content',
    'text_content_en',
    'media_url',
    'is_real',
    'mil_tip',
    'mil_tip_en',
    'category',
    'author_name',
    'author_handle',
    'likes_count',
    'created_at',
]
PublicationScalarFieldKeys = Literal[
    'id',
    'text_content',
    'text_content_en',
    'media_url',
    'is_real',
    'mil_tip',
    'mil_tip_en',
    'category',
    'author_name',
    'author_handle',
    'likes_count',
    'created_at',
]
PublicationScalarFieldKeysT = TypeVar('PublicationScalarFieldKeysT', bound=PublicationScalarFieldKeys)

PublicationRelationalFieldKeys = _NoneType

# LeaderboardEntry types

class LeaderboardEntryOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the LeaderboardEntry create method"""
    id: _int
    created_at: datetime.datetime


class LeaderboardEntryCreateInput(LeaderboardEntryOptionalCreateInput):
    """Required arguments to the LeaderboardEntry create method"""
    player_name: _str
    score: _int
    correct: _int
    wrong: _int
    omitted: _int
    accuracy_pct: _float
    duration_s: _int


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class LeaderboardEntryOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the LeaderboardEntry create method, without relations"""
    id: _int
    created_at: datetime.datetime


class LeaderboardEntryCreateWithoutRelationsInput(LeaderboardEntryOptionalCreateWithoutRelationsInput):
    """Required arguments to the LeaderboardEntry create method, without relations"""
    player_name: _str
    score: _int
    correct: _int
    wrong: _int
    omitted: _int
    accuracy_pct: _float
    duration_s: _int

class LeaderboardEntryConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'LeaderboardEntryCreateWithoutRelationsInput'
    where: 'LeaderboardEntryWhereUniqueInput'

class LeaderboardEntryCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'LeaderboardEntryCreateWithoutRelationsInput'
    connect: 'LeaderboardEntryWhereUniqueInput'
    connect_or_create: 'LeaderboardEntryConnectOrCreateWithoutRelationsInput'


class LeaderboardEntryCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['LeaderboardEntryCreateWithoutRelationsInput', List['LeaderboardEntryCreateWithoutRelationsInput']]
    connect: Union['LeaderboardEntryWhereUniqueInput', List['LeaderboardEntryWhereUniqueInput']]
    connect_or_create: Union['LeaderboardEntryConnectOrCreateWithoutRelationsInput', List['LeaderboardEntryConnectOrCreateWithoutRelationsInput']]

_LeaderboardEntryWhereUnique_id_Input = TypedDict(
    '_LeaderboardEntryWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

LeaderboardEntryWhereUniqueInput = _LeaderboardEntryWhereUnique_id_Input


class LeaderboardEntryUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    player_name: _str
    score: Union[AtomicIntInput, _int]
    correct: Union[AtomicIntInput, _int]
    wrong: Union[AtomicIntInput, _int]
    omitted: Union[AtomicIntInput, _int]
    accuracy_pct: Union[AtomicFloatInput, _float]
    duration_s: Union[AtomicIntInput, _int]
    created_at: datetime.datetime


class LeaderboardEntryUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    player_name: _str
    score: Union[AtomicIntInput, _int]
    correct: Union[AtomicIntInput, _int]
    wrong: Union[AtomicIntInput, _int]
    omitted: Union[AtomicIntInput, _int]
    accuracy_pct: Union[AtomicFloatInput, _float]
    duration_s: Union[AtomicIntInput, _int]
    created_at: datetime.datetime


class LeaderboardEntryUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['LeaderboardEntryCreateWithoutRelationsInput']
    connect: List['LeaderboardEntryWhereUniqueInput']
    connect_or_create: List['LeaderboardEntryConnectOrCreateWithoutRelationsInput']
    set: List['LeaderboardEntryWhereUniqueInput']
    disconnect: List['LeaderboardEntryWhereUniqueInput']
    delete: List['LeaderboardEntryWhereUniqueInput']

    # TODO
    # update: List['LeaderboardEntryUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['LeaderboardEntryUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['LeaderboardEntryScalarWhereInput']
    # upsert: List['LeaderboardEntryUpserteWithWhereUniqueWithoutRelationsInput']


class LeaderboardEntryUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'LeaderboardEntryCreateWithoutRelationsInput'
    connect: 'LeaderboardEntryWhereUniqueInput'
    connect_or_create: 'LeaderboardEntryConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'LeaderboardEntryUpdateInput'
    # upsert: 'LeaderboardEntryUpsertWithoutRelationsInput'


class LeaderboardEntryUpsertInput(TypedDict):
    create: 'LeaderboardEntryCreateInput'
    update: 'LeaderboardEntryUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_LeaderboardEntry_id_OrderByInput = TypedDict(
    '_LeaderboardEntry_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_player_name_OrderByInput = TypedDict(
    '_LeaderboardEntry_player_name_OrderByInput',
    {
        'player_name': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_score_OrderByInput = TypedDict(
    '_LeaderboardEntry_score_OrderByInput',
    {
        'score': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_correct_OrderByInput = TypedDict(
    '_LeaderboardEntry_correct_OrderByInput',
    {
        'correct': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_wrong_OrderByInput = TypedDict(
    '_LeaderboardEntry_wrong_OrderByInput',
    {
        'wrong': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_omitted_OrderByInput = TypedDict(
    '_LeaderboardEntry_omitted_OrderByInput',
    {
        'omitted': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_accuracy_pct_OrderByInput = TypedDict(
    '_LeaderboardEntry_accuracy_pct_OrderByInput',
    {
        'accuracy_pct': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_duration_s_OrderByInput = TypedDict(
    '_LeaderboardEntry_duration_s_OrderByInput',
    {
        'duration_s': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_created_at_OrderByInput = TypedDict(
    '_LeaderboardEntry_created_at_OrderByInput',
    {
        'created_at': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_RelevanceInner = TypedDict(
    '_LeaderboardEntry_RelevanceInner',
    {
        'fields': 'List[LeaderboardEntryScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_LeaderboardEntry_RelevanceOrderByInput = TypedDict(
    '_LeaderboardEntry_RelevanceOrderByInput',
    {
        '_relevance': '_LeaderboardEntry_RelevanceInner',
    },
    total=True
)

LeaderboardEntryOrderByInput = Union[
    '_LeaderboardEntry_id_OrderByInput',
    '_LeaderboardEntry_player_name_OrderByInput',
    '_LeaderboardEntry_score_OrderByInput',
    '_LeaderboardEntry_correct_OrderByInput',
    '_LeaderboardEntry_wrong_OrderByInput',
    '_LeaderboardEntry_omitted_OrderByInput',
    '_LeaderboardEntry_accuracy_pct_OrderByInput',
    '_LeaderboardEntry_duration_s_OrderByInput',
    '_LeaderboardEntry_created_at_OrderByInput',
    '_LeaderboardEntry_RelevanceOrderByInput',
]



# recursive LeaderboardEntry types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

LeaderboardEntryRelationFilter = TypedDict(
    'LeaderboardEntryRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class LeaderboardEntryListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class LeaderboardEntryInclude(TypedDict, total=False):
    """LeaderboardEntry relational arguments"""


    

class PublicationIncludeFromLeaderboardEntry(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class PublicationIncludeFromLeaderboardEntryRecursive1(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class PublicationIncludeFromLeaderboardEntryRecursive2(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class PublicationIncludeFromLeaderboardEntryRecursive3(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class PublicationIncludeFromLeaderboardEntryRecursive4(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""

    

class PublicationArgsFromLeaderboardEntry(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'PublicationIncludeFromPublicationRecursive1'


class PublicationArgsFromLeaderboardEntryRecursive1(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'PublicationIncludeFromPublicationRecursive2'


class PublicationArgsFromLeaderboardEntryRecursive2(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'PublicationIncludeFromPublicationRecursive3'


class PublicationArgsFromLeaderboardEntryRecursive3(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'PublicationIncludeFromPublicationRecursive4'


class PublicationArgsFromLeaderboardEntryRecursive4(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    
    

class FindManyPublicationArgsFromLeaderboardEntry(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive1'


class FindManyPublicationArgsFromLeaderboardEntryRecursive1(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive2'


class FindManyPublicationArgsFromLeaderboardEntryRecursive2(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive3'


class FindManyPublicationArgsFromLeaderboardEntryRecursive3(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    include: 'PublicationIncludeFromPublicationRecursive4'


class FindManyPublicationArgsFromLeaderboardEntryRecursive4(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['PublicationOrderByInput', List['PublicationOrderByInput']]
    where: 'PublicationWhereInput'
    cursor: 'PublicationWhereUniqueInput'
    distinct: List['PublicationScalarFieldKeys']
    
    

class LeaderboardEntryIncludeFromLeaderboardEntry(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class LeaderboardEntryIncludeFromLeaderboardEntryRecursive1(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class LeaderboardEntryIncludeFromLeaderboardEntryRecursive2(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class LeaderboardEntryIncludeFromLeaderboardEntryRecursive3(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""


class LeaderboardEntryIncludeFromLeaderboardEntryRecursive4(TypedDict, total=False):
    """Relational arguments for LeaderboardEntry"""

    

class LeaderboardEntryArgsFromLeaderboardEntry(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive1'


class LeaderboardEntryArgsFromLeaderboardEntryRecursive1(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive2'


class LeaderboardEntryArgsFromLeaderboardEntryRecursive2(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive3'


class LeaderboardEntryArgsFromLeaderboardEntryRecursive3(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive4'


class LeaderboardEntryArgsFromLeaderboardEntryRecursive4(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    
    

class FindManyLeaderboardEntryArgsFromLeaderboardEntry(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive1'


class FindManyLeaderboardEntryArgsFromLeaderboardEntryRecursive1(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive2'


class FindManyLeaderboardEntryArgsFromLeaderboardEntryRecursive2(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive3'


class FindManyLeaderboardEntryArgsFromLeaderboardEntryRecursive3(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    include: 'LeaderboardEntryIncludeFromLeaderboardEntryRecursive4'


class FindManyLeaderboardEntryArgsFromLeaderboardEntryRecursive4(TypedDict, total=False):
    """Arguments for LeaderboardEntry"""
    take: int
    skip: int
    order_by: Union['LeaderboardEntryOrderByInput', List['LeaderboardEntryOrderByInput']]
    where: 'LeaderboardEntryWhereInput'
    cursor: 'LeaderboardEntryWhereUniqueInput'
    distinct: List['LeaderboardEntryScalarFieldKeys']
    


FindManyLeaderboardEntryArgs = FindManyLeaderboardEntryArgsFromLeaderboardEntry
FindFirstLeaderboardEntryArgs = FindManyLeaderboardEntryArgsFromLeaderboardEntry


    

class LeaderboardEntryWhereInput(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    player_name: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    correct: Union[_int, 'types.IntFilter']
    wrong: Union[_int, 'types.IntFilter']
    omitted: Union[_int, 'types.IntFilter']
    accuracy_pct: Union[_float, 'types.FloatFilter']
    duration_s: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['LeaderboardEntryWhereInputRecursive1', List['LeaderboardEntryWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['LeaderboardEntryWhereInputRecursive1']
    OR: List['LeaderboardEntryWhereInputRecursive1']
    NOT: List['LeaderboardEntryWhereInputRecursive1']


class LeaderboardEntryWhereInputRecursive1(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    player_name: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    correct: Union[_int, 'types.IntFilter']
    wrong: Union[_int, 'types.IntFilter']
    omitted: Union[_int, 'types.IntFilter']
    accuracy_pct: Union[_float, 'types.FloatFilter']
    duration_s: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['LeaderboardEntryWhereInputRecursive2', List['LeaderboardEntryWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['LeaderboardEntryWhereInputRecursive2']
    OR: List['LeaderboardEntryWhereInputRecursive2']
    NOT: List['LeaderboardEntryWhereInputRecursive2']


class LeaderboardEntryWhereInputRecursive2(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    player_name: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    correct: Union[_int, 'types.IntFilter']
    wrong: Union[_int, 'types.IntFilter']
    omitted: Union[_int, 'types.IntFilter']
    accuracy_pct: Union[_float, 'types.FloatFilter']
    duration_s: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['LeaderboardEntryWhereInputRecursive3', List['LeaderboardEntryWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['LeaderboardEntryWhereInputRecursive3']
    OR: List['LeaderboardEntryWhereInputRecursive3']
    NOT: List['LeaderboardEntryWhereInputRecursive3']


class LeaderboardEntryWhereInputRecursive3(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    player_name: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    correct: Union[_int, 'types.IntFilter']
    wrong: Union[_int, 'types.IntFilter']
    omitted: Union[_int, 'types.IntFilter']
    accuracy_pct: Union[_float, 'types.FloatFilter']
    duration_s: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['LeaderboardEntryWhereInputRecursive4', List['LeaderboardEntryWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['LeaderboardEntryWhereInputRecursive4']
    OR: List['LeaderboardEntryWhereInputRecursive4']
    NOT: List['LeaderboardEntryWhereInputRecursive4']


class LeaderboardEntryWhereInputRecursive4(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    player_name: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    correct: Union[_int, 'types.IntFilter']
    wrong: Union[_int, 'types.IntFilter']
    omitted: Union[_int, 'types.IntFilter']
    accuracy_pct: Union[_float, 'types.FloatFilter']
    duration_s: Union[_int, 'types.IntFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']



# aggregate LeaderboardEntry types


    

class LeaderboardEntryScalarWhereWithAggregatesInput(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    player_name: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']
    correct: Union[_int, 'types.IntWithAggregatesFilter']
    wrong: Union[_int, 'types.IntWithAggregatesFilter']
    omitted: Union[_int, 'types.IntWithAggregatesFilter']
    accuracy_pct: Union[_float, 'types.FloatWithAggregatesFilter']
    duration_s: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive1']
    OR: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive1']
    NOT: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive1']


class LeaderboardEntryScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    player_name: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']
    correct: Union[_int, 'types.IntWithAggregatesFilter']
    wrong: Union[_int, 'types.IntWithAggregatesFilter']
    omitted: Union[_int, 'types.IntWithAggregatesFilter']
    accuracy_pct: Union[_float, 'types.FloatWithAggregatesFilter']
    duration_s: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive2']
    OR: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive2']
    NOT: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive2']


class LeaderboardEntryScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    player_name: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']
    correct: Union[_int, 'types.IntWithAggregatesFilter']
    wrong: Union[_int, 'types.IntWithAggregatesFilter']
    omitted: Union[_int, 'types.IntWithAggregatesFilter']
    accuracy_pct: Union[_float, 'types.FloatWithAggregatesFilter']
    duration_s: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive3']
    OR: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive3']
    NOT: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive3']


class LeaderboardEntryScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    player_name: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']
    correct: Union[_int, 'types.IntWithAggregatesFilter']
    wrong: Union[_int, 'types.IntWithAggregatesFilter']
    omitted: Union[_int, 'types.IntWithAggregatesFilter']
    accuracy_pct: Union[_float, 'types.FloatWithAggregatesFilter']
    duration_s: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive4']
    OR: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive4']
    NOT: List['LeaderboardEntryScalarWhereWithAggregatesInputRecursive4']


class LeaderboardEntryScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """LeaderboardEntry arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    player_name: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']
    correct: Union[_int, 'types.IntWithAggregatesFilter']
    wrong: Union[_int, 'types.IntWithAggregatesFilter']
    omitted: Union[_int, 'types.IntWithAggregatesFilter']
    accuracy_pct: Union[_float, 'types.FloatWithAggregatesFilter']
    duration_s: Union[_int, 'types.IntWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class LeaderboardEntryGroupByOutput(TypedDict, total=False):
    id: _int
    player_name: _str
    score: _int
    correct: _int
    wrong: _int
    omitted: _int
    accuracy_pct: _float
    duration_s: _int
    created_at: datetime.datetime
    _sum: 'LeaderboardEntrySumAggregateOutput'
    _avg: 'LeaderboardEntryAvgAggregateOutput'
    _min: 'LeaderboardEntryMinAggregateOutput'
    _max: 'LeaderboardEntryMaxAggregateOutput'
    _count: 'LeaderboardEntryCountAggregateOutput'


class LeaderboardEntryAvgAggregateOutput(TypedDict, total=False):
    """LeaderboardEntry output for aggregating averages"""
    id: float
    score: float
    correct: float
    wrong: float
    omitted: float
    accuracy_pct: float
    duration_s: float


class LeaderboardEntrySumAggregateOutput(TypedDict, total=False):
    """LeaderboardEntry output for aggregating sums"""
    id: _int
    score: _int
    correct: _int
    wrong: _int
    omitted: _int
    accuracy_pct: _float
    duration_s: _int


class LeaderboardEntryScalarAggregateOutput(TypedDict, total=False):
    """LeaderboardEntry output including scalar fields"""
    id: _int
    player_name: _str
    score: _int
    correct: _int
    wrong: _int
    omitted: _int
    accuracy_pct: _float
    duration_s: _int
    created_at: datetime.datetime


LeaderboardEntryMinAggregateOutput = LeaderboardEntryScalarAggregateOutput
LeaderboardEntryMaxAggregateOutput = LeaderboardEntryScalarAggregateOutput


class LeaderboardEntryMaxAggregateInput(TypedDict, total=False):
    """LeaderboardEntry input for aggregating by max"""
    id: bool
    player_name: bool
    score: bool
    correct: bool
    wrong: bool
    omitted: bool
    accuracy_pct: bool
    duration_s: bool
    created_at: bool


class LeaderboardEntryMinAggregateInput(TypedDict, total=False):
    """LeaderboardEntry input for aggregating by min"""
    id: bool
    player_name: bool
    score: bool
    correct: bool
    wrong: bool
    omitted: bool
    accuracy_pct: bool
    duration_s: bool
    created_at: bool


class LeaderboardEntryNumberAggregateInput(TypedDict, total=False):
    """LeaderboardEntry input for aggregating numbers"""
    id: bool
    score: bool
    correct: bool
    wrong: bool
    omitted: bool
    accuracy_pct: bool
    duration_s: bool


LeaderboardEntryAvgAggregateInput = LeaderboardEntryNumberAggregateInput
LeaderboardEntrySumAggregateInput = LeaderboardEntryNumberAggregateInput


LeaderboardEntryCountAggregateInput = TypedDict(
    'LeaderboardEntryCountAggregateInput',
    {
        'id': bool,
        'player_name': bool,
        'score': bool,
        'correct': bool,
        'wrong': bool,
        'omitted': bool,
        'accuracy_pct': bool,
        'duration_s': bool,
        'created_at': bool,
        '_all': bool,
    },
    total=False,
)

LeaderboardEntryCountAggregateOutput = TypedDict(
    'LeaderboardEntryCountAggregateOutput',
    {
        'id': int,
        'player_name': int,
        'score': int,
        'correct': int,
        'wrong': int,
        'omitted': int,
        'accuracy_pct': int,
        'duration_s': int,
        'created_at': int,
        '_all': int,
    },
    total=False,
)


LeaderboardEntryKeys = Literal[
    'id',
    'player_name',
    'score',
    'correct',
    'wrong',
    'omitted',
    'accuracy_pct',
    'duration_s',
    'created_at',
]
LeaderboardEntryScalarFieldKeys = Literal[
    'id',
    'player_name',
    'score',
    'correct',
    'wrong',
    'omitted',
    'accuracy_pct',
    'duration_s',
    'created_at',
]
LeaderboardEntryScalarFieldKeysT = TypeVar('LeaderboardEntryScalarFieldKeysT', bound=LeaderboardEntryScalarFieldKeys)

LeaderboardEntryRelationalFieldKeys = _NoneType



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields